heat_template_version: 2015-04-30

description: Simple template to deploy a single compute instance

resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      key_name: mykey
      image: cirros-0.3.4-x86_64-uec 
      flavor: m1.tiny

