CREATE 
  (`0` :service {name:'nova',configfile:"/etc/nova/nova.conf "}) ,
  (`1` :service {name:'neutron'}) ,
  (`2` :service {name:'keystone',configfile:"/etc/keystone/keystone.conf"}) ,
  (`3` :service {name:'glance',configfile:"/etc/glance/glance-api.conf"}) ,
  (`4` :service {name:'cinder'}) ,
  (`5` :service {name:'ceilometer'}) ,
  (`6` :service {name:'swift'}) ,
  
  (`8` :process {name:'mongodb'}) ,
  (`9` :process {name:'rabbitmqctl'}) ,
  (`10` :process {name:'memcached',configfile:"/etc/memcached.conf"}) ,
  (`11` :process {name:'apache',configfile:"/etc/apache2/apache2.conf"}) ,
  (`12` :process {name:'nova-api'}) ,
  (`13` :process {name:'nova-consoleauth'}) ,
  (`14` :process {name:'nova-scheduler'}) ,
  (`15` :process {name:'nova-conductor'}) ,
  (`16` :process {name:'nova-novncproxy'}) ,
  (`17` :process {name:'neutron-server'}) ,
  
  (`18` :process {name:'neutron-linuxbridge-agent'}) ,
  (`19` :process {name:'neutron-dhcp-agent'}) ,
  (`20` :process {name:'neutron-metadata-agent'}) ,
  (`21` :process {name:'neutron-l3-agent'}) ,
  
  (`22` :node {name:'controller node',ip:'10.0.0.11'}) ,
  (`23` :process {name:'glance-control'}) ,
  (`24` :process {name:'glance-registry',configfile:"/etc/glance/glance-registry.conf"}) ,
  (`25` :process {name:'glance-api',configfile:"/etc/glance/glance-api.conf"}) ,
  (`26` :process {name:'cinder-scheduler'}) ,
  (`27` :process {name:'cinder-api'}) ,
  (`28` :process {name:'tgt'}) ,
  
  (`29` :process {name:'process'}) ,
  (`30` :process {name:'ceilometer-agent-central'}) ,
  (`31` :process {name:'ceilometer-agent-notification'}) ,
  (`32` :process {name:'ceilometer-api'}) ,
  (`33` :process {name:'ceilometer-collector'}) ,
  
  (`34` :process {name:'swift-proxy'}) ,
  (`35` :process {name:'swift-init'}) ,
  (`36` :process {name:'ntp/chrony',configfile:"/etc/chrony/chrony.conf"}) ,
  
  (`38` :node {name:'compute1',ip:'10.0.0.31'}) ,
  (`39` :node {name:'block node',ip:'10.0.0.11'}) ,
  (`40` :node {name:'object1 node',ip:'10.0.0.51'}) ,
  (`41` :node {name:'object2 node',ip:'10.0.0.52'}) ,
  (`42` :process {name:'mariadb',configfile:"/etc/mysql/mariadb.conf.d/99-openstack.cnf"}) ,
  
  (`0`)-[:`MANAGED_BY`]->(`12`),
  (`0`)-[:`MANAGED_BY`]->(`13`),
  (`0`)-[:`MANAGED_BY`]->(`14`),
  (`0`)-[:`MANAGED_BY`]->(`15`),
  (`0`)-[:`MANAGED_BY`]->(`16`),
  (`1`)-[:`MANAGED_BY`]->(`17`),
  (`1`)-[:`MANAGED_BY`]->(`18`),
  (`1`)-[:`MANAGED_BY`]->(`19`),
  (`1`)-[:`MANAGED_BY`]->(`20`),
  (`1`)-[:`MANAGED_BY`]->(`21`),
  (`3`)-[:`MANAGED_BY`]->(`23`),
  (`3`)-[:`MANAGED_BY`]->(`24`),
  (`3`)-[:`MANAGED_BY`]->(`25`),
  (`4`)-[:`MANAGED_BY`]->(`26`),
  (`4`)-[:`MANAGED_BY`]->(`27`),
  (`4`)-[:`MANAGED_BY`]->(`28`),
  (`4`)-[:`MANAGED_BY`]->(`29`),
  (`5`)-[:`MANAGED_BY`]->(`30`),
  (`5`)-[:`MANAGED_BY`]->(`31`),
  (`5`)-[:`MANAGED_BY`]->(`32`),
  (`5`)-[:`MANAGED_BY`]->(`33`),
  (`6`)-[:`MANAGED_BY`]->(`34`),
  (`6`)-[:`MANAGED_BY`]->(`35`),
  (`22`)-[:`ALLOWED_BY`]->(`36`),
  (`38`)-[:`ALLOWED_BY`]->(`36`),
  (`39`)-[:`ALLOWED_BY`]->(`36`),
  (`40`)-[:`ALLOWED_BY`]->(`36`),
  (`41`)-[:`ALLOWED_BY`]->(`36`),
  (`42`)-[:`CONFIGURED_ON`]->(`22`),
  (`36`)-[:`CONFIGURED_ON`]->(`22`),
  (`9`)-[:`CONFIGUREDON`]->(`22`),
  (`10`)-[:`CONFIGURED_ON`]->(`22`),
  (`2`)-[:`AUTHENTICATED`]->(`42`),
  (`2`)-[:`CONFIGURED_ON`]->(`22`),
  (`11`)-[:`CONFIGURED_ON`]->(`22`),
  (`11`)-[:`USES`]->(`22`),
  (`3`)-[:`CONFIGURED_ON`]->(`22`),
  (`25`)-[:`AUTHENTICATED`]->(`42`),
  (`24`)-[:`AUTHENTICATED`]->(`42`),
  (`0`)-[:`AUTHENTICATED`]->(`42`),
  (`0`)-[:`AUTHENTICATED`]->(`2`),
  (`25`)-[:`AUTHENTICATED`]->(`2`),
  (`0`)-[:`AUTHENTICATED`]->(`10`),
  (`25`)-[:`AUTHENTICATED`]->(`10`),
  (`20`)-[:`AUTHENTICATED`]->(`2`)
